services:
  - type: web
    name: 3d-chart-app
    env: python
    buildCommand: ""
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: PORT
        value: 10000
